### ISSUE TITLE
Fix all command as Lua

### ISSUE THREAD

**Issue by juhaku** [mantoni/eslint_d.js#231]
Can you explain what does this command do exactly:
```
nnoremap <leader>f mF:%!eslint_d --stdin --fix-to-stdout<CR>`F
```
And also what does this \`mF:%......\`F mean?

Also how to convert this to lua?

Thank you for your help

**Comment by mantoni** [comment]
This does a couple of things:

- `<leader>f` configures a shortcut
- `mF` sets a "marker" for the current cursor position
- `:%eslint_d ...` sends the current buffer to `eslint_d` with the special non-eslint option `--fix-to-stdout` to send eslint fixes to stdout
- `\`F` restores the previously stored cursor position

So effectively the current in-memory buffer is send to eslint for fixing and the result replaces the buffer. Since this causes the current cursor position to be lost, we remember it and restore it after the operation.

TBH I don't really use this myself anymore. ¯\_(ツ)_/¯ 

Hope this helps!

**Comment by juhaku** [comment]
Thanks that already explains a lot. :+1:  Thanks
