### ISSUE TITLE
Ability to register/unregister clients to automate server stop

### ISSUE THREAD

**Issue by watson28** [mantoni/eslint_d.js#236]
I have noticed that after closing all the clients that talk to eslint_d, the server keeps running with significant memory usage.

It would be good to have the ability to optionally register a client when talking with eslint_d for the first time. The daemon could keep a list of all clients that are connected. When a client notifies that wants to disconnect, the daemon will check if it's the last one connected and then stop itself. 

could this be considered a feature to implement?

**Comment by mantoni** [comment]
I gave this some thought, and I think you can probably get away with a simpler solution: Instead of introducing "book-keeping" for clients, we could add a command to "flush" or "evict" a cached instance.

Instances are internally associated with a working directory, so a command like `eslint_d evict .` could remove the cached instance for the project in the current directory. You can then trigger that command when your editor exits.

Would you be interested in contributing this feature?

**Comment by victorlacorte** [comment]
Hey @mantoni I'd be interested in contributing to this feature. Do you know if any work has been done since this thread was opened?

**Comment by mantoni** [comment]
Awesome! I'm not aware of anyone working on this yet. Let me know if you have any questions. ❤️

**Comment by mantoni** [comment]
This has been addressed with the new major `v14.0.0` (see #294). You can now use `ESLINT_D_PPID` to bind the daemon to your editor process.
