### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by DamienCassou** [mantoni/eslint_d.js#322]
I sometimes have issues with eslint_d. To understand what is happening, I'm adding some log instructions to the code. It would be nice if eslint_d had a debug mode builtin. This can be done by writing log to stderr if that doesn't conflict with the client/daemon communication. Otherwise, this can be done by writing log to a temporary file.

**Comment by mantoni** [comment]
Absolutely. I was wondering if eslint_d should follow the same model es eslint here and use the debug module and have it enabled with `--debug`. This would allow to see what happens in which library.

**Comment by DamienCassou** [comment]
I agree. `--debug` could activate the debug logging. eslint is doing it this way:

```js
// must do this initialization *before* other requires in order to work
if (process.argv.includes("--debug")) {
    require("debug").enable("eslint:*,-eslint:code-path,eslintrc:*");
}
```

The debug library has some information about child processes that may be useful: https://www.npmjs.com/package/debug#user-content-usage-in-child-processes.

**Comment by mantoni** [comment]
The child process stderr stream cannot be used in our case because the process is detached from the process that launches the daemon. So all output goes nowhere.

We already stream stdout and stderr back to the requesting client here:

https://github.com/mantoni/eslint_d.js/blob/4af421ab15b45c7b7e7a72c98257ba8153929550/lib/service.js#L58-L59

The only "black box" are things that happen outside of client requests, like the process ending itself. I'd say a first implementation could ignore that edge case and simply enable debugging and add some debug calls.

**Comment by L2jLiga** [comment]
May be write stdout/stderr to file could be the option?
Log file could be in tmp or in the same place where pid file stored, this way it can be opened in text editor and/or printed to console by `eslint_d log` command for example

**Comment by mantoni** [comment]
I made a thing in #323. Please have look / play with it and let me know what you think. 🙏

**Comment by DamienCassou** [comment]
Brilliant!
