### ISSUE TITLE
Improve documentation on configuration handling

### ISSUE THREAD

**Issue by fatso83** [mantoni/eslint_d.js#34]
I am missing some documentation on how this thing works. Specifically:

- what happens if I supply a different config file between invocations? Will it restart the process?
- what happens if I change the working directory?
- is there a way of listing which files are touched/being done something with? `--debug` did not really show anything.

**Comment by ruanyl** [comment]
Maybe I could answer some of the questions, @mantoni please correct me if I am wrong ;)

1. It basically pass the new config file that you specified by -c flag to eslint engine. If there is no config file specified, then eslint will try to find one, just the same as eslint. And it will not restart the process

2. If you changed to a new  working directory, `eslint_d` will try to resolve `eslint` again based on the new working dir. You could find the codes here: https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js#L34

And I agree, maybe add some documentations about what eslint_d did in the background would be helpful :)

**Comment by mantoni** [comment]
Thanks @ruanyl, that is correct.

To be very clear on one thing: `eslint_d` improves the performance of eslint by caching the eslint instance per directory. If the eslint version or config changes, the only save option is `eslint_d restart`.

This whole thing started as a hack because I was very unhappy with the eslint performance in vim. Now that it's becoming a little more popular, it clearly needs better documentation. As always, help is very much appreciated.

**Comment by fatso83** [comment]
Sure :-) Thanks for the feedback. I can see what I can do, but no promises.

**Comment by mantoni** [comment]
Managed to write something and would like to hear your thoughts @fatso83 and @ruanyl: https://github.com/mantoni/eslint_d.js/pull/57

**Comment by mantoni** [comment]
Closing as https://github.com/mantoni/eslint_d.js/pull/57 was approved.
