### ISSUE TITLE
eslint version as peerDependency?

### ISSUE THREAD

**Issue by jonathanewerner** [mantoni/eslint_d.js#38]
I'd like to use eslint 2.7.0 -- it seems that because it's specified in `dependencies` here, that's not possible when using eslint_d?
What would speak against putting it into peerDeps?

**Comment by mantoni** [comment]
The dependency is specified as `^2.2` which translates to `>=2.2 <3`. This means reinstalling eslint_d will install the latest eslint.

If you want to use a specific version of eslint in a project, you can define the version in the devDependencies. Eslint_d will use a project-local version if it finds one and fall back to it's own dependency otherwise.

Hope this helps.

**Comment by jonathanewerner** [comment]
Thanks, you're right, it was in a bit of a messy upgrade situation and missed the "^" bit -- just saw eslint in eslint_d node_modules folder.
