### ISSUE TITLE
Intermittent issues with eslint_d

### ISSUE THREAD

**Issue by tribou** [mantoni/eslint_d.js#39]
I've been having some intermittent issues with eslint_d, and I had a couple questions.

- Does eslint_d resolve local project eslint-config modules automatically?

I didn't know if eslint_d needed to be supplemented with a config similar to [mtscout6/syntastic-local-eslint.vim](https://github.com/mtscout6/syntastic-local-eslint.vim) to ensure it always resolves the local project config modules.

- What's the best way to debug eslint_d?

I'm encountering intermittent issues where I have to run `eslint_d restart` in order to get eslint_d to work again with Syntastic.  After enabling `g:syntastic_debug` and determining the eslint_d command being used, I found there were errors similar to this:

```bash
eslint_d -f compact src/config/env.js
Error: standard:
	Configuration for rule "no-labels" is invalid:
	Value "2,[object Object]" has more items than allowed.

Referenced from: tribou
Referenced from: /Users/tribou/dev/project/.eslintrc
```

The error is from the `eslint-config-standard` module, but it's [associated with using eslint v1.x](https://github.com/feross/eslint-config-standard/issues/23#issuecomment-180918500), so I'm not sure what to do with that.  However, after running `eslint_d restart` in the project directory, the issue appears to resolve itself.  Any ideas?

`v2.8.0 (eslint_d v3.1.0)`

**Comment by mantoni** [comment]
Hm, I would guess that eslint_d loaded an older version - e.g. from your `node_modules` directory. If eslint was updated to a newer version afterwards, you need to restart eslint_d to discard the old instance and load the new version.

To your questions:

> Does eslint_d resolve local project eslint-config modules automatically?

It leaves the config resolution to eslint. It *should* work just like eslint, otherwise there's a bug (see https://github.com/mantoni/eslint_d.js/issues/21)

> What's the best way to debug eslint_d?

Enabling `g:syntastic_debug` is a very good idea. Other than that, there is clearly some more advanced error handling needed in eslint_d. It does not forward any error output from the background process.

**Comment by mantoni** [comment]
As it's not clear what the issue actually is, please update to latest `eslint_d` and report back if it's still not working as expected. I'm happy to reopen.
