### ISSUE TITLE
eslint_d using a different node_modules folder than eslint

### ISSUE THREAD

**Issue by joerideg** [mantoni/eslint_d.js#41]
Hi! 
Awesome work, love the speed =)

Let me first specify the version I get when running `eslint_d -v`:
`v2.10.2 (eslint_d v3.1.0)`

Say I have a folder which contains a node_modules folder with eslint installed.

- myProject
  - node_modules
     - eslint
  - src/ with bunch of js files

There is no .eslintrc in that folder, but there is one in my home directory ~/myHome/.eslintrc
The .eslintrc extends some config, or uses a certain plugin, lets say eslint-config-angular that is installed globally but not in myProject.

Now, if I would run `eslint src/**/*js` inside myProject, it all works fine. It searches up the tree to my home, finds the .eslintrc and tries to find eslint and its plugins etc from the global installed packages. So basicly it seems to search relative to the .eslinrc, and since its in home it uses global installed packages.

If I run `eslint_d src/**/*.js` however I get an error `Error: Cannot find module 'eslint-config-angular' from '/home/myHome/myProject/node_modules'`. It seems that eslint_d searches for eslint and companions relative to the folder its executed in, not relative to the .eslintrc it uses.

**Comment by mantoni** [comment]
Yes, what you're observing is correct and this is by design, but maybe you have an idea how to make it work differently in your case. Let me explain:

The way the `eslint_d` command achives the performance improvement is by loading `eslint` only once per project. So it checks for a locally installed eslint first and falls back to it's own eslint dependency if it can't find it in `node_modules`. When you run `eslint`, you're using a global install. I guess you would have the same issue with `node_modules/.bin/eslint src/**/*.js`.

Now the question is, how should `eslint_d` decide which installation to use? If it would check for configs, it might produce unexpected results for other use cases. One example: configuring eslint in the `package.json`.

Does that help clarify what is going on?

**Comment by mantoni** [comment]
I'm going to close for now as it's not clear that this is really an issue. Please update to latest eslint_d and if it still doesn't work for you I will reopen.

**Comment by lukebrooker** [comment]
I have the same problem. Would it be possible to somehow check if the plugins are installed globally if it can't find them locally?
