### ISSUE TITLE
flow-bin executes in visible command window in Windows

### ISSUE THREAD

**Issue by chrisvasz** [mantoni/eslint_d.js#60]
When using `eslint-plugin-flowtype-errors` in Windows, eslint executes `flow` to determine FlowJS errors. When running `eslint_d`, this causes a visible command window to appear and steal focus from the editor. This happens when executing `eslint_d` from a command window also.

This behavior does *not* happen when executing `eslint` from the command line.

I would be happy to send a PR, but I need a pointer in the right direction. I glanced through the code and the solution was not obvious to me.

**Comment by mantoni** [comment]
It's neither obvious to me. A pull request would be most welcome, since I don't have a Windows machine at hand to verify. It's also not clear to me why this should happen. 🤔

**Comment by aaronjensen** [comment]
@chrisvasz I don't know what would cause this either, but I could provide some ideas on how to track it down. 

Since you can repro from the command line, it's a matter of finding the actual code that pops the window.

First, try deleting all but the `#!/usr/bin/env node` from `node_modules/.bin/eslint_d` (or whatever the windows equivalent is) and try running `eslint_d` again. If it still pops up the window, then perhaps there is some setting in the package that we must set in order to tell windows to do something special w/ the bin.

If it doesn't, then we know it's something that that file is doing.

You'd then have to figure out which commands (all of them? Just one?) pop the command window.

Try `start`, `-v`, `-h` and `.` maybe. These cover the 4 branches of the bin.

From there, I'd just dig into each of the branches that fails and try deleting code until I can find the code that pops the command window. 

Good luck, please let us know what you find.

**Comment by mantoni** [comment]
We can not do much with this issue right now. A pull request would be welcome and discussion could continue there. Closing for now.
