### ISSUE TITLE
Initialization Cannot Find Module

### ISSUE THREAD

**Issue by idkjs** [mantoni/eslint_d.js#66]
After installing and selecting eslint_d as eslint, webstorm throws error looking for the cli. There is no cli option in the package that i could tell. What am I missing here to get this  to work with webstorm? Thank you.

![screen shot 2017-04-18 at 13 16 56](https://cloud.githubusercontent.com/assets/2370391/25128368/c9a92878-2439-11e7-8db9-0a576ec54b0a.png)

![screen shot 2017-04-18 at 13 20 53](https://cloud.githubusercontent.com/assets/2370391/25128420/f8ae5a9e-2439-11e7-944f-a03b2d5da09f.png)

**Comment by mantoni** [comment]
The newest version of WebStorm seems to have a new eslint integration. It's unclear atm whether eslint_d still improves performance when used with that version. If you could try to find out more I would be thankful as I'm not using WebStorm myself.

**Comment by idkjs** [comment]
What do you want to know? If its faster with or without? I guess I cant really do anything if there isnt the cli file that webstorm is looking for, right? Happy to help if you show me how. Thanks for taking the time to respond.

**Comment by mantoni** [comment]
There have been [recent comments on the PR that added WebStorm support](https://github.com/mantoni/eslint_d.js/pull/24) initially. I guess the discussion should proceed here though since it's a new issue.

As @SimenB comment in the original PR:

> I don't think it's possible, but the newer intellij uses the api more directly out of the box, so not as needed as before, maybe?
> 
> https://blog.jetbrains.com/webstorm/2017/02/webstorm-2017-1-eap-171-3224/

This raises two questions:

1) Is it still possible to use `eslint_d` with the new version of WebStorm somehow?
2) If it can be fixed, is it really worth it?

**Comment by idkjs** [comment]
When I tried to use it, it was asking for the cli file which doesnt exist in this eslint version so i guess i would have to figure out why it needs that to see if its necessary. That is way out of my skill set at this point in my learning so wont be able to help you there. Generally though, its pretty damned fast now so I cant say it will matter.

**Comment by kidroca** [comment]
Hello,
I tinkered with this a bit today and here are my findings:

### 1. Is it possible to use `eslint_d` with the new version of WebStorm somehow?

- **Yes**. But it will require modification to Webstorm's plugin code. New plugin for `eslint_d` and update the *plugin provider* to provide eslint or eslint_d plugin based on the use case. So probably not gonna happen

- There is no way to modify `eslint_d` to work with the current Webstorm eslint plugin,
because the plugin uses/calls `eslint.CLIEngine` directly, and not via `cli`

- If you have Webstrom, you can view it's eslint plugin here: `[webstorm install dir]/plugins/JavaScriptLanguage/languageService/eslint`

#### Closer look at the webstorm eslint plugin: 
- it's written in typescript/js 
- it has only `sync` actions (This may be for a reason)
- *it doesn't actually use the `lib/cli`* apart from validation reasons 
- it uses `lib/cli-engine` and `lib/options` similar to the way they are used in `eslint_d/lib/linter`

### 2. If it can be fixed, is it really worth it?

- **No**

99% It's not worth it, it seems that Webstorm's plugin does pretty much the same. It runs javascript inside some environment it receives events managed by the `languageService` and then runs lint/fix/format commands (the commands are executed sync)

### PS

While I was tinkering with the code, I created the infamous `lib/cli.js` using `eslint/lib/cli` as example;
- bin/eslint -> https://github.com/kidroca/eslint_d.js/blob/feat/cli/bin/eslint.js
- lib/cli -> https://github.com/kidroca/eslint_d.js/blob/feat/cli/lib/cli.js

I can convert this to es5 and send you a pull request if you like

**Comment by mantoni** [comment]
@kidroca Thanks for the detailed analysis. As you mentioned, it's not really worth fixing, because it's now fast enough in WebStorm by default. Maybe we should mention the differences in the WebStorm versions in the README to avoid frustration for others who come across this module.

However, if you're keen to send a PR with a fix, that is absolutely welcome, too. I'm just not able to maintain WebStorm support myself. I rely on the help of the community here.
